version: '3.9'
services:
  a1111:
    container_name: sd-a1111
    image: 
    ports:
      - "7890:7890"
    volumes:
      - ./data:/data
      - ./output:/output
    stop_signal: SIGINT
    environment:
      - CLI_ARGS=--listen --port 7890 --enable-insecure-extension-access --api --theme=dark --no-half-vae
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu,compute,utility]